-- MySQL Script generated by MySQL Workbench
-- 11/04/14 15:20:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dentomax2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dentomax2` DEFAULT CHARACTER SET latin1 ;
USE `dentomax2` ;

-- -----------------------------------------------------
-- Table `dentomax2`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`cargo` (
  `id_cargo` INT(2) NOT NULL AUTO_INCREMENT,
  `nom_cargo` CHAR(25) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`estado_civil` (
  `id_civil` INT(1) NOT NULL AUTO_INCREMENT,
  `tipo_civil` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_civil`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`estado_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`estado_medico` (
  `id_em` INT(5) NOT NULL AUTO_INCREMENT,
  `estado_med` CHAR(15) NOT NULL,
  PRIMARY KEY (`id_em`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`hora` (
  `id_hora` INT(1) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_dtll` INT(9) NOT NULL,
  PRIMARY KEY (`id_hora`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`tipo_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`tipo_medico` (
  `id_tm` INT(5) NOT NULL AUTO_INCREMENT,
  `tipo_med` CHAR(20) NOT NULL,
  PRIMARY KEY (`id_tm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`medico` (
  `rut_med` VARCHAR(10) NOT NULL,
  `nom_med` CHAR(30) NOT NULL,
  `ap_med` CHAR(20) NOT NULL,
  `am_med` CHAR(20) NOT NULL,
  `dir_med` VARCHAR(45) NOT NULL,
  `celu_med` INT(8) NOT NULL,
  `fijo_med` INT(7) NULL DEFAULT NULL,
  `mail_med` VARCHAR(25) NOT NULL,
  `em_id_em` INT(5) NOT NULL,
  `tm_id_tm` INT(5) NOT NULL,
  PRIMARY KEY (`rut_med`),
  INDEX `em_id_em` (`em_id_em` ASC),
  INDEX `tm_id_tm` (`tm_id_tm` ASC),
  CONSTRAINT `medico_ibfk_1`
    FOREIGN KEY (`em_id_em`)
    REFERENCES `dentomax2`.`estado_medico` (`id_em`),
  CONSTRAINT `medico_ibfk_2`
    FOREIGN KEY (`tm_id_tm`)
    REFERENCES `dentomax2`.`tipo_medico` (`id_tm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`paciente` (
  `rut_pac` VARCHAR(10) NOT NULL,
  `nom_pac` CHAR(30) NOT NULL,
  `ap_pac` CHAR(20) NOT NULL,
  `am_pac` CHAR(20) NOT NULL,
  `est_civ_pac` INT(1) NOT NULL,
  `fech_nac_pac` DATE NOT NULL,
  `sex_pac` CHAR(6) NOT NULL,
  `dir_pac` VARCHAR(45) NOT NULL,
  `mail_pac` VARCHAR(45) NULL DEFAULT NULL,
  `cod_fono_pac` INT(3) NULL,
  `fono` INT(7) NULL DEFAULT NULL,
  `celu_pac` INT(8) NULL DEFAULT NULL,
  PRIMARY KEY (`rut_pac`),
  INDEX `est_civ_pac` (`est_civ_pac` ASC),
  CONSTRAINT `paciente_ibfk_1`
    FOREIGN KEY (`est_civ_pac`)
    REFERENCES `dentomax2`.`estado_civil` (`id_civil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`presupuesto` (
  `id_presu` INT(11) NOT NULL AUTO_INCREMENT,
  `presu_rut_pac` VARCHAR(10) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_presu`),
  INDEX `presu_rut_pac` (`presu_rut_pac` ASC),
  CONSTRAINT `presupuesto_ibfk_1`
    FOREIGN KEY (`presu_rut_pac`)
    REFERENCES `dentomax2`.`paciente` (`rut_pac`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`tratamiento` (
  `id_trata` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_trata` CHAR(35) NOT NULL,
  `valor_trata` INT(9) NOT NULL,
  `medico_rut_med` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_trata`),
  INDEX `fk_tratamiento_medico1_idx` (`medico_rut_med` ASC),
  CONSTRAINT `fk_tratamiento_medico1`
    FOREIGN KEY (`medico_rut_med`)
    REFERENCES `dentomax2`.`medico` (`rut_med`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`detalle_presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`detalle_presupuesto` (
  `id_presu` INT(5) NOT NULL,
  `presupuesto_id_presu` INT(11) NOT NULL,
  `estado_deta_presu` CHAR(10) NULL,
  `tratamiento_id_trata` INT(11) NOT NULL,
  `valor_descuento` INT(6) NULL DEFAULT 0,
  PRIMARY KEY (`id_presu`),
  INDEX `fk_detalle_presupuesto_presupuesto1_idx` (`presupuesto_id_presu` ASC),
  INDEX `fk_detalle_presupuesto_tratamiento1_idx` (`tratamiento_id_trata` ASC),
  CONSTRAINT `fk_detalle_presupuesto_presupuesto1`
    FOREIGN KEY (`presupuesto_id_presu`)
    REFERENCES `dentomax2`.`presupuesto` (`id_presu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_presupuesto_tratamiento1`
    FOREIGN KEY (`tratamiento_id_trata`)
    REFERENCES `dentomax2`.`tratamiento` (`id_trata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`ubicacion_pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`ubicacion_pieza` (
  `id_ubica_pieza` INT(2) NOT NULL,
  `nom_ubica` CHAR(15) NOT NULL,
  PRIMARY KEY (`id_ubica_pieza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`laboratorio` (
  `id_labora` INT(6) NOT NULL,
  `nom_labora` CHAR(20) NULL,
  `direc_labora` VARCHAR(35) NULL,
  `cod_fono_labora` INT(3) NULL,
  `fono_labora` INT(5) NULL,
  `mail_labora` VARCHAR(30) NULL,
  PRIMARY KEY (`id_labora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`molde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`molde` (
  `id_molde` INT(6) NOT NULL,
  `fecha_captura` DATE NOT NULL,
  `detalle_molde` VARCHAR(45) NULL,
  `laboratorio_id_labora` INT(6) NOT NULL,
  PRIMARY KEY (`id_molde`),
  INDEX `fk_molde_laboratorio1_idx` (`laboratorio_id_labora` ASC),
  CONSTRAINT `fk_molde_laboratorio1`
    FOREIGN KEY (`laboratorio_id_labora`)
    REFERENCES `dentomax2`.`laboratorio` (`id_labora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`pieza` (
  `num_pieza` INT(2) NOT NULL,
  `detalle_presupuesto_id_presu` INT(5) NOT NULL,
  `ubicacion_pieza_id_ubica_pieza` INT(2) NOT NULL,
  `molde_id_molde` INT(6) NOT NULL,
  `imagen_pieza` LONGBLOB NOT NULL,
  PRIMARY KEY (`num_pieza`),
  INDEX `fk_pieza_detalle_presupuesto1_idx` (`detalle_presupuesto_id_presu` ASC),
  INDEX `fk_pieza_ubicacion_pieza1_idx` (`ubicacion_pieza_id_ubica_pieza` ASC),
  INDEX `fk_pieza_molde1_idx` (`molde_id_molde` ASC),
  CONSTRAINT `fk_pieza_detalle_presupuesto1`
    FOREIGN KEY (`detalle_presupuesto_id_presu`)
    REFERENCES `dentomax2`.`detalle_presupuesto` (`id_presu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pieza_ubicacion_pieza1`
    FOREIGN KEY (`ubicacion_pieza_id_ubica_pieza`)
    REFERENCES `dentomax2`.`ubicacion_pieza` (`id_ubica_pieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pieza_molde1`
    FOREIGN KEY (`molde_id_molde`)
    REFERENCES `dentomax2`.`molde` (`id_molde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`cara_pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`cara_pieza` (
  `id_cara_pieza` INT(11) NOT NULL AUTO_INCREMENT,
  `cara_pieza` CHAR(10) NOT NULL,
  PRIMARY KEY (`id_cara_pieza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`usuario` (
  `rut_usu` VARCHAR(10) NOT NULL,
  `nom_usu` CHAR(20) NOT NULL,
  `ap_usu` CHAR(35) NOT NULL,
  `am_usu` CHAR(35) NOT NULL,
  `tipo_usu` INT(2) NOT NULL,
  `pas_usu` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`rut_usu`),
  INDEX `tipo_usu` (`tipo_usu` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`tipo_usu`)
    REFERENCES `dentomax2`.`cargo` (`id_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`paciente_has_hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`paciente_has_hora` (
  `paciente_rut_pac` VARCHAR(10) NOT NULL,
  `hora_id_hora` INT(11) NOT NULL,
  PRIMARY KEY (`paciente_rut_pac`, `hora_id_hora`),
  INDEX `fk_paciente_has_hora_hora1_idx` (`hora_id_hora` ASC),
  INDEX `fk_paciente_has_hora_paciente1_idx` (`paciente_rut_pac` ASC),
  CONSTRAINT `fk_paciente_has_hora_paciente1`
    FOREIGN KEY (`paciente_rut_pac`)
    REFERENCES `dentomax2`.`paciente` (`rut_pac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_has_hora_hora1`
    FOREIGN KEY (`hora_id_hora`)
    REFERENCES `dentomax2`.`hora` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`articulo` (
  `id_arti` INT NOT NULL,
  `nom_arti` CHAR(45) NULL,
  `cantidad_arti` INT NULL,
  PRIMARY KEY (`id_arti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`estado_implante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`estado_implante` (
  `id_estado_impla` INT(6) NOT NULL,
  `nom_estado_impla` CHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado_impla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`implante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`implante` (
  `id_implante` INT(6) NOT NULL,
  `detalle_implante` VARCHAR(45) NULL,
  `molde_id_molde` INT(6) NOT NULL,
  `implantecol` VARCHAR(45) NULL,
  `estado_implante_id_estado_impla` INT(6) NOT NULL,
  PRIMARY KEY (`id_implante`),
  INDEX `fk_implante_molde1_idx` (`molde_id_molde` ASC),
  INDEX `fk_implante_estado_implante1_idx` (`estado_implante_id_estado_impla` ASC),
  CONSTRAINT `fk_implante_molde1`
    FOREIGN KEY (`molde_id_molde`)
    REFERENCES `dentomax2`.`molde` (`id_molde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_implante_estado_implante1`
    FOREIGN KEY (`estado_implante_id_estado_impla`)
    REFERENCES `dentomax2`.`estado_implante` (`id_estado_impla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentomax2`.`pieza_has_cara_pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`pieza_has_cara_pieza` (
  `pieza_id_pieza` INT(2) NOT NULL,
  `cara_pieza_id_cara_pieza` INT(11) NOT NULL,
  INDEX `fk_pieza_has_cara_pieza_cara_pieza1_idx` (`cara_pieza_id_cara_pieza` ASC),
  INDEX `fk_pieza_has_cara_pieza_pieza1_idx` (`pieza_id_pieza` ASC),
  PRIMARY KEY (`pieza_id_pieza`, `cara_pieza_id_cara_pieza`),
  CONSTRAINT `fk_pieza_has_cara_pieza_pieza1`
    FOREIGN KEY (`pieza_id_pieza`)
    REFERENCES `dentomax2`.`pieza` (`num_pieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pieza_has_cara_pieza_cara_pieza1`
    FOREIGN KEY (`cara_pieza_id_cara_pieza`)
    REFERENCES `dentomax2`.`cara_pieza` (`id_cara_pieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dentomax2`.`disponible_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentomax2`.`disponible_medico` (
  `id_dispo_med` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `medico_rut_med` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_dispo_med`),
  INDEX `fk_disponible_medico_medico1_idx` (`medico_rut_med` ASC),
  CONSTRAINT `fk_disponible_medico_medico1`
    FOREIGN KEY (`medico_rut_med`)
    REFERENCES `dentomax2`.`medico` (`rut_med`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
